site_name: Crypt4GH Processing
theme:
  name: "material"
nav:
  - "C4GH": index.md
  - "Implementation": implementation.md
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths:
            - oarepo_c4gh
          options:
            allow_inspection: false
            show_source: true
            filters:
              - "!^__"
              - "__init__"
              - "__bytes__"
            show_signature_annotations: true
            show_root_heading: true
            ignore_init_summary: false
