site_name: Crypt4GH Processing
theme:
  name: "material"
nav:
  - "Public API": index.md
  - "Exceptions": exceptions.md
  - "Keys": keys.md
  - "Container": container.md
  - "Network Protocol Specification": network.md
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths:
            - oarepo_c4gh
          options:
            allow_inspection: false
            show_source: true
            filters:
              - "!^__"
              - "__init__"
              - "__bytes__"
            show_signature_annotations: true
            show_root_heading: true
            ignore_init_summary: false
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
