alice_pub_bstr = (
    b"-----BEGIN CRYPT4GH PUBLIC KEY-----\n"
    b"oyERnWAhzV4MAh9XIk0xD4C+nNp2tpLUiWtQoVS/xB4=\n"
    b"-----END CRYPT4GH PUBLIC KEY-----\n"
)


alice_sec_bstr = (
    b"-----BEGIN ENCRYPTED PRIVATE KEY-----\n"
    b"YzRnaC12MQAGYmNyeXB0ABQAAABk8Kn90WJVzJBevxN4980aWwARY2hhY2hhMjBfcG9seTEzMDUAPBdXfpV1zOcMg5EJRlGNpKZXT4PXM2iraMGCyomRQqWaH5iBGmJXU/JROPsyoX5nqmNo8oxANvgDi1hqZQ==\n"
    b"-----END ENCRYPTED PRIVATE KEY-----"
)


alice_sec_bstr_dos = (
    b"-----BEGIN ENCRYPTED PRIVATE KEY-----\r\n"
    b"YzRnaC12MQAGYmNyeXB0ABQAAABk8Kn90WJVzJBevxN4980aWwARY2hhY2hhMjBfcG9seTEzMDUAPBdXfpV1zOcMg5EJRlGNpKZXT4PXM2iraMGCyomRQqWaH5iBGmJXU/JROPsyoX5nqmNo8oxANvgDi1hqZQ==\r\n"
    b"-----END ENCRYPTED PRIVATE KEY-----"
)


alice_sec_password = "alice"

# Generated by reference implementation using:
# crypt4gh encrypt --sk ../crypt4gh/tests/_common/bob.sec --recipient_pk ../crypt4gh/tests/_common/alice.pub <hello.txt >hello.txt.c4gh
hello_world_encrypted = (
    b"crypt4gh\x01\x00\x00\x00\x01\x00\x00\x00"
    b"\x6c\x00\x00\x00\x00\x00\x00\x00\x25\x71\x9e\xee\xfa\x4d\x66\x95"
    b"\x84\x86\xcc\x6b\x20\x4f\xe1\xf3\x7c\x6c\xb7\xbb\x10\xfb\x62\x0d"
    b"\xa5\xaa\x22\x1a\x3b\x4b\x20\x38\x55\xeb\x07\x6e\xe2\x66\xdc\xa0"
    b"\xe0\x61\xd3\x74\x1d\xdd\xed\x48\x7c\x00\xc9\x85\x1c\x83\x77\xb8"
    b"\xed\xe9\x67\x9e\x55\xef\x71\x67\x1b\x3c\x31\x11\xad\x99\x16\x9a"
    b"\xb4\xed\x37\x64\xc5\x6d\x8a\x10\xbb\x35\x5e\xe0\x65\x52\x44\x03"
    b"\xae\xeb\x8f\xe4\xb4\x5c\xe5\x4f\xd9\x09\xf1\x1c\xde\xef\x4c\x03"
    b"\x19\x87\xe4\x66\xb9\xe0\x28\xf5\xb7\x62\x06\x76\x44\xa3\x10\xb8"
    b"\xe1\xd8\x23\x04\x17\x7c\x7c\x09\xe7\xf1\x5a\x03\xac\xb7\x66\xbb"
    b"\x2b\xee\x1a\x5e\x89"
)
